/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

Object.defineProperty(exports, "__esModule", { value: true });
module.exports = require('../../../../../../get-babel-options/bit.envs/0.0.1/src/internal/getBabelOptions/index');