/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

module.exports = require('../../components/.dependencies/internal/babel-base-compiler/bit.envs/0.0.1/src/internal/babelBaseCompiler/index');